### PR TITLE
#6 #7 Real world examples, readme structure

### PR DESCRIPTION
**Pull request by Cleop**
#7 Adds real world examples
#6 Tidies up structure to direct people with different technical levels
#10 Adds info about what to do with sensitive data

### CODE REVIEW

**Review by iteles — COMMENTED** [review]
Looks good so far @Cleop, please assign to me when ready 👍

**Review by nelsonic — APPROVED** [review]
@Cleop real-world examples section looks good. and re-formatting previous lines also good. thanks! 🎉

**Comment by Cleop** [comment]
@iteles - I've rewritten the bit about hiding sensitive data as I now have a better understanding of how to do this. Nothing else has changed 👍

**Review by iteles — APPROVED** [review]
Thanks for the clarification @Cleop looks good!

**Pull request merged**
